#!/bin/bash
RUN=0
VHDL_VERSION=08
VSG_CONFIG=vsg-config.yaml
VSG_STYLE=jcl
RESCALE_FROM="1 fs"
RESCALE_TO="10 ns"

printf "=== VSG: Styling $1.vhd and $1_tb.vhd\n"
vsg -f $1.vhd $1_tb.vhd --style $VSG_STYLE -c $VSG_CONFIG --fix --backup

printf "=== GHDL: Analyzing $1.vhd and $1_tb.vhd\n"
ghdl -a --std=$VHDL_VERSION --mb-comments -fsynopsys TTCPU_lib.vhd fmt.vhd $1.vhd $1_tb.vhd

[[ $RUN -eq 0 ]] && exit 

printf "=== GHDL: Display FILEs in HTML with xrefs\n"
ghdl --xref-html --std=$VHDL_VERSION --mb-comments -fsynopsys TTCPU_lib.vhd fmt.vhd $1.vhd $1_tb.vhd

printf "=== GHDL: Running $1_tb.vhd\n"
ghdl -r --std=$VHDL_VERSION --mb-comments -fsynopsys $1_tb --vcd=$1.vcd --stop-time=1us

printf "=== VCD: Rescaling to 10 ns\n"
rescale-vcd "$RESCALE_FROM" "$RESCALE_TO" < $1.vcd > $1_rescaled.vcd &&\

printf "=== GTKWAVE: Showing waveform of $1_tb.vhd\n"
gtkwave $1_rescaled.vcd &
